teams:
  - name: 'Super Life Group'
    slug: 'super-life-group'
    domain: 'superlifegroup.com'
    defaultRole: 'MEMBER'
    users:
      - name: 'Jin Kim'
        email: '1jin-soo.kim@mailinator.com'
        password: 'jin@123'
        emailVerified: '2024-01-01T00:00:00Z'
        role: 'OWNER'
      - name: 'Madison Henry'
        email: '1madison.henry@mailinator.com'
        password: 'madison@123'
        emailVerified: '2024-01-01T00:00:00Z'
        role: 'ADMIN'
      - name: 'Avery Lee'
        email: '1avery.lee@mailinator.com'
        password: 'avery@123'
        emailVerified: '2024-01-01T00:00:00Z'
        role: 'MEMBER'
      - name: 'Youseff Marrak'
        email: '1youseff.marrak@mailinator.com'
        password: 'youseff@123'
        emailVerified: null
        role: 'MEMBER'
      - name: 'Zeb Rowen'
        email: '1zeb.rowen@mailinator.com'
        password: 'zeb@123'
        emailVerified: null
        role: 'MEMBER'
      - name: 'Jordan Ortiz'
        email: '1jordan.ortiz@mailinator.com'
        password: 'jordan@123'
        emailVerified: null
        role: 'MEMBER'
      - name: 'Gary Gunnison'
        email: '1gary.gunnison@mailinator.com'
        password: 'gary@123'
        emailVerified: null
        role: 'ADMIN'
      - name: 'Alexis Torres'
        email: '1alexis.torres@mailinator.com'
        password: 'alexis@123'
        emailVerified: null
        role: 'MEMBER'
      - name: 'Xiu Ying'
        email: '1xiu.ying@mailinator.com'
        password: 'xiu@123'
        emailVerified: null
        role: 'MEMBER'
      - name: 'Rajesh Kumar'
        email: '1rajesh.kumar@mailinator.com'
        password: 'rajesh@123'
        emailVerified: null
        role: 'MEMBER'

  - name: 'Maverick Realty'
    slug: 'maverick-realty'
    domain: 'maverickrealty.com'
    defaultRole: 'MEMBER'
    users:
      - name: 'Jin Kim'
        email: '2jin-soo.kim@mailinator.com'
        password: 'jin@123'
        emailVerified: '2024-01-01T00:00:00Z'
        role: 'OWNER'
      - name: 'Madison Henry'
        email: '2madison.henry@mailinator.com'
        password: 'madison@123'
        emailVerified: '2024-01-01T00:00:00Z'
        role: 'ADMIN'
      - name: 'Avery Lee'
        email: '2avery.lee@mailinator.com'
        password: 'avery@123'
        emailVerified: '2024-01-01T00:00:00Z'
        role: 'MEMBER'
      - name: 'Youseff Marrak'
        email: '2youseff.marrak@mailinator.com'
        password: 'youseff@123'
        emailVerified: null
        role: 'MEMBER'
      - name: 'Zeb Rowen'
        email: '2zeb.rowen@mailinator.com'
        password: 'zeb@123'
        emailVerified: null
        role: 'MEMBER'
      - name: 'Jordan Ortiz'
        email: '2jordan.ortiz@mailinator.com'
        password: 'jordan@123'
        emailVerified: null
        role: 'MEMBER'
      - name: 'Gary Gunnison'
        email: '2gary.gunnison@mailinator.com'
        password: 'gary@123'
        emailVerified: null
        role: 'ADMIN'
      - name: 'Alexis Torres'
        email: '2alexis.torres@mailinator.com'
        password: 'alexis@123'
        emailVerified: null
        role: 'MEMBER'
      - name: 'Xiu Ying'
        email: '2xiu.ying@mailinator.com'
        password: 'xiu@123'
        emailVerified: null
        role: 'MEMBER'
      - name: 'Rajesh Kumar'
        email: '2rajesh.kumar@mailinator.com'
        password: 'rajesh@123'
        emailVerified: null
        role: 'MEMBER'

  - name: 'Ignite West Region Sales'
    slug: 'ignite-west-region-sales'
    domain: 'ignitewestregionsales.com'
    defaultRole: 'MEMBER'
    users:
      - name: 'Jin Kim'
        email: '3jin-soo.kim@mailinator.com'
        password: 'jin@123'
        emailVerified: '2024-01-01T00:00:00Z'
        role: 'OWNER'
      - name: 'Madison Henry'
        email: '3madison.henry@mailinator.com'
        password: 'madison@123'
        emailVerified: '2024-01-01T00:00:00Z'
        role: 'ADMIN'
      - name: 'Avery Lee'
        email: '3avery.lee@mailinator.com'
        password: 'avery@123'
        emailVerified: '2024-01-01T00:00:00Z'
        role: 'MEMBER'
      - name: 'Youseff Marrak'
        email: '3youseff.marrak@mailinator.com'
        password: 'youseff@123'
        emailVerified: null
        role: 'MEMBER'
      - name: 'Zeb Rowen'
        email: '3zeb.rowen@mailinator.com'
        password: 'zeb@123'
        emailVerified: null
        role: 'MEMBER'
      - name: 'Jordan Ortiz'
        email: '3jordan.ortiz@mailinator.com'
        password: 'jordan@123'
        emailVerified: null
        role: 'MEMBER'
      - name: 'Gary Gunnison'
        email: '3gary.gunnison@mailinator.com'
        password: 'gary@123'
        emailVerified: null
        role: 'ADMIN'
      - name: 'Alexis Torres'
        email: '3alexis.torres@mailinator.com'
        password: 'alexis@123'
        emailVerified: null
        role: 'MEMBER'
      - name: 'Xiu Ying'
        email: '3xiu.ying@mailinator.com'
        password: 'xiu@123'
        emailVerified: null
        role: 'MEMBER'
      - name: 'Rajesh Kumar'
        email: '3rajesh.kumar@mailinator.com'
        password: 'rajesh@123'
        emailVerified: null
        role: 'MEMBER'

  - name: 'Continental Insurance'
    slug: 'continental-insurance'
    domain: 'continentalinsurance.com'
    defaultRole: 'MEMBER'
    users:
      - name: 'Jin Kim'
        email: '4jin-soo.kim@mailinator.com'
        password: 'jin@123'
        emailVerified: '2024-01-01T00:00:00Z'
        role: 'OWNER'
      - name: 'Madison Henry'
        email: '4madison.henry@mailinator.com'
        password: 'madison@123'
        emailVerified: '2024-01-01T00:00:00Z'
        role: 'ADMIN'
      - name: 'Avery Lee'
        email: '4avery.lee@mailinator.com'
        password: 'avery@123'
        emailVerified: '2024-01-01T00:00:00Z'
        role: 'MEMBER'
      - name: 'Youseff Marrak'
        email: '4youseff.marrak@mailinator.com'
        password: 'youseff@123'
        emailVerified: null
        role: 'MEMBER'
      - name: 'Zeb Rowen'
        email: '4zeb.rowen@mailinator.com'
        password: 'zeb@123'
        emailVerified: null
        role: 'MEMBER'
      - name: 'Jordan Ortiz'
        email: '4jordan.ortiz@mailinator.com'
        password: 'jordan@123'
        emailVerified: null
        role: 'MEMBER'
      - name: 'Gary Gunnison'
        email: '4gary.gunnison@mailinator.com'
        password: 'gary@123'
        emailVerified: null
        role: 'ADMIN'
      - name: 'Alexis Torres'
        email: '4alexis.torres@mailinator.com'
        password: 'alexis@123'
        emailVerified: null
        role: 'MEMBER'
      - name: 'Xiu Ying'
        email: '4xiu.ying@mailinator.com'
        password: 'xiu@123'
        emailVerified: null
        role: 'MEMBER'
      - name: 'Rajesh Kumar'
        email: '4rajesh.kumar@mailinator.com'
        password: 'rajesh@123'
        emailVerified: null
        role: 'MEMBER'

  - name: 'Insights Product Team'
    slug: 'insights-product-team'
    domain: 'insightsproductteam.com'
    defaultRole: 'MEMBER'
    users:
      - name: 'Jin Kim'
        email: '5jin-soo.kim@mailinator.com'
        password: 'jin@123'
        emailVerified: '2024-01-01T00:00:00Z'
        role: 'OWNER'
      - name: 'Madison Henry'
        email: '5madison.henry@mailinator.com'
        password: 'madison@123'
        emailVerified: '2024-01-01T00:00:00Z'
        role: 'ADMIN'
      - name: 'Avery Lee'
        email: '5avery.lee@mailinator.com'
        password: 'avery@123'
        emailVerified: '2024-01-01T00:00:00Z'
        role: 'MEMBER'
      - name: 'Youseff Marrak'
        email: '5youseff.marrak@mailinator.com'
        password: 'youseff@123'
        emailVerified: null
        role: 'MEMBER'
      - name: 'Zeb Rowen'
        email: '5zeb.rowen@mailinator.com'
        password: 'zeb@123'
        emailVerified: null
        role: 'MEMBER'
      - name: 'Jordan Ortiz'
        email: '5jordan.ortiz@mailinator.com'
        password: 'jordan@123'
        emailVerified: null
        role: 'MEMBER'
      - name: 'Gary Gunnison'
        email: '5gary.gunnison@mailinator.com'
        password: 'gary@123'
        emailVerified: null
        role: 'ADMIN'
      - name: 'Alexis Torres'
        email: '5alexis.torres@mailinator.com'
        password: 'alexis@123'
        emailVerified: null
        role: 'MEMBER'
      - name: 'Xiu Ying'
        email: '5xiu.ying@mailinator.com'
        password: 'xiu@123'
        emailVerified: null
        role: 'MEMBER'
      - name: 'Rajesh Kumar'
        email: '5rajesh.kumar@mailinator.com'
        password: 'rajesh@123'
        emailVerified: null
        role: 'MEMBER'

  - name: 'Global Financial Impact'
    slug: 'global-financial-impact'
    domain: 'globalfinancialimpact.com'
    defaultRole: 'MEMBER'
    users:
      - name: 'Jin Kim'
        email: '6jin-soo.kim@mailinator.com'
        password: 'jin@123'
        emailVerified: '2024-01-01T00:00:00Z'
        role: 'OWNER'
      - name: 'Madison Henry'
        email: '6madison.henry@mailinator.com'
        password: 'madison@123'
        emailVerified: '2024-01-01T00:00:00Z'
        role: 'ADMIN'
      - name: 'Avery Lee'
        email: '6avery.lee@mailinator.com'
        password: 'avery@123'
        emailVerified: '2024-01-01T00:00:00Z'
        role: 'MEMBER'
