# Program Template
#
# Use this template to create new program YAML files.
# Copy this file and customize for your client's program.
#
# IMPORTANT: Program and stage names must match EXACTLY in the task file (case-sensitive)

programs:
  - name: 'Program Name'  # REQUIRED: Full program name (must match task file)
    subtitle: 'Brief subtitle describing the program'  # REQUIRED: One-line description
    description: 'Detailed description of what the program accomplishes and who it is for. Explain the value and outcomes participants can expect.'  # REQUIRED: Full description
    status: 'ACTIVE'  # REQUIRED: DRAFT, ACTIVE, or ARCHIVED
    
    stages:
      # Stage 1
      - name: 'Stage 1 Name'  # REQUIRED: Stage name (must match task file)
        order: 1  # REQUIRED: Sequential order (1, 2, 3, ...)
        status: 'ACTIVE'  # REQUIRED: DRAFT, ACTIVE, or ARCHIVED
        expectedDuration: 7  # REQUIRED: Duration in days
        desiredOutcomes:  # REQUIRED: List of 3-5 specific outcomes
          - 'Specific outcome 1'
          - 'Specific outcome 2'
          - 'Specific outcome 3'
      
      # Stage 2
      - name: 'Stage 2 Name'
        order: 2
        status: 'ACTIVE'
        expectedDuration: 7
        desiredOutcomes:
          - 'Specific outcome 1'
          - 'Specific outcome 2'
          - 'Specific outcome 3'
      
      # Stage 3
      - name: 'Stage 3 Name'
        order: 3
        status: 'ACTIVE'
        expectedDuration: 7
        desiredOutcomes:
          - 'Specific outcome 1'
          - 'Specific outcome 2'
          - 'Specific outcome 3'
      
      # Stage 4 (optional - add or remove stages as needed)
      - name: 'Stage 4 Name'
        order: 4
        status: 'ACTIVE'
        expectedDuration: 14
        desiredOutcomes:
          - 'Specific outcome 1'
          - 'Specific outcome 2'
          - 'Specific outcome 3'

# NOTES:
# 
# 1. Program Name
#    - Must match exactly in task file
#    - Case-sensitive
#    - Example: 'New Agent Onboarding'
#
# 2. Stage Names
#    - Must match exactly in task file
#    - Case-sensitive
#    - Be descriptive (e.g., 'Week 1: Foundation' not just 'Week 1')
#
# 3. Order Numbers
#    - Must be sequential integers (1, 2, 3, ...)
#    - No gaps or duplicates
#
# 4. Expected Duration
#    - In days
#    - Be realistic based on task complexity
#
# 5. Desired Outcomes
#    - 3-5 outcomes per stage
#    - Be specific and measurable
#    - Focus on what participant will achieve
#
# 6. Status Values
#    - DRAFT: Program is being developed
#    - ACTIVE: Program is ready for use
#    - ARCHIVED: Program is no longer active
#
# EXAMPLE PROGRAMS:
# - See config/seed-data/programs/gfi-new-agent-school-program.yml
# - See config/seed-data/programs/super-life-group-program.yml
#
# NEXT STEPS:
# 1. Copy this template to programs/[client-name]-program.yml
# 2. Fill in all fields
# 3. Validate YAML syntax
# 4. Create corresponding task file using task-template.yml
# 5. Add to seed-from-yaml.ts programFiles array
