name: Test Organization Secrets

on:
  workflow_dispatch:

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Test ANA_WEBHOOK_SECRET
        run: |
          if [ -n "${{ secrets.ANA_WEBHOOK_SECRET }}" ]; then
            echo "✅ ANA_WEBHOOK_SECRET is accessible"
            echo "Length: ${#ANA_WEBHOOK_SECRET}"
          else
            echo "❌ ANA_WEBHOOK_SECRET is not accessible"
          fi
        env:
          ANA_WEBHOOK_SECRET: ${{ secrets.ANA_WEBHOOK_SECRET }}

      - name: Test ORG_PAT
        run: |
          if [ -n "${{ secrets.ORG_PAT }}" ]; then
            echo "✅ ORG_PAT is accessible"
            echo "Length: ${#ORG_PAT}"
          else
            echo "❌ ORG_PAT is not accessible"
          fi
        env:
          ORG_PAT: ${{ secrets.ORG_PAT }}

      - name: Test T0D_WEBHOOK_ENDPOINT
        run: |
          if [ -n "${{ secrets.T0D_WEBHOOK_ENDPOINT }}" ]; then
            echo "✅ T0D_WEBHOOK_ENDPOINT is accessible"
            echo "Length: ${#T0D_WEBHOOK_ENDPOINT}"
          else
            echo "❌ T0D_WEBHOOK_ENDPOINT is not accessible"
          fi
        env:
          T0D_WEBHOOK_ENDPOINT: ${{ secrets.T0D_WEBHOOK_ENDPOINT }}

      - name: Test VERCEL_API_TOKEN (should fail)
        run: |
          if [ -n "${{ secrets.VERCEL_API_TOKEN }}" ]; then
            echo "✅ VERCEL_API_TOKEN is accessible"
            echo "Length: ${#VERCEL_API_TOKEN}"
          else
            echo "❌ VERCEL_API_TOKEN is not accessible (expected)"
          fi
        env:
          VERCEL_API_TOKEN: ${{ secrets.VERCEL_API_TOKEN }}
